### ISSUE TITLE
VBO's are used inside display list

### ISSUE THREAD

**Issue by scrawl** [openscenegraph/OpenSceneGraph#528]
As seen on this [apitrace](https://i.imgur.com/uV3l05q.png), OSG 3.6 uses VBOs inside a display list. The normal use would be to use either VBOs or display lists. This odd behavior crashes some Mesa graphics drivers.

To reproduce above apitrace it's sufficient to create a simple Geometry with all default settings.

**Comment by openscenegraph** [comment]
opps, that a surprising one to sleep through testing.  What Mesa graphics drivers/hardwire have this issue?

I will look into rendering internals of osg::Geometry to see what is going on.

**Comment by JDGBOLT** [comment]
I was the user who encountered this crash, it's on a Amd Fury GPU running amdgpu with Mesa 18.0.0. It seems there is some interaction between a model made for Morrowind as a mod and the aforementioned issue that is causing it to crash. As far as where it crashes it's within this function: https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osg/Geometry.cpp#L982 . And the actual commit where the crash first appeared was https://github.com/openscenegraph/OpenSceneGraph/commit/94891778c40ff08fcc626f91ded73cda67713b36 . Setting OSG_VERTEX_BUFFER_HINT to VBO causes it to work correctly, but with NO_PREFERENCE, which is the default, it causes the crash.

As far as the actual backtrace of the crash, though without debugging information, is: 

openmw: ../mesa-18.0.0/src/mesa/state_tracker/st_cb_bufferobjects.c:461: st_bufferobj_map_range: Assertion `offset < obj->Size' failed.

Thread 13 "openmw" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb7fff700 (LWP 3764)]
0x00007ffff1773860 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff1773860 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff1774ec9 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff176c0bc in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007ffff176c133 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00007fffe1f1c366 in ?? () from /usr/lib/dri/radeonsi_dri.so
#5  0x00007fffe1da0924 in ?? () from /usr/lib/dri/radeonsi_dri.so
#6  0x00007fffe1e6f71a in ?? () from /usr/lib/dri/radeonsi_dri.so
#7  0x00007ffff79b0caa in osg::Geometry::drawPrimitivesImplementation(osg::RenderInfo&) const () from /usr/lib/libosg.so.156
#8  0x00007ffff79b1f03 in osg::Geometry::drawImplementation(osg::RenderInfo&) const () from /usr/lib/libosg.so.156
#9  0x00007ffff799c120 in osg::Drawable::draw(osg::RenderInfo&) const () from /usr/lib/libosg.so.156
#10 0x00007ffff7103dc8 in osgUtil::RenderLeaf::render(osg::RenderInfo&, osgUtil::RenderLeaf*) () from /usr/lib/libosgUtil.so.156
#11 0x00007ffff70fdc65 in osgUtil::RenderBin::drawImplementation(osg::RenderInfo&, osgUtil::RenderLeaf*&) () from /usr/lib/libosgUtil.so.156
#12 0x00007ffff710b4ac in osgUtil::RenderStage::drawImplementation(osg::RenderInfo&, osgUtil::RenderLeaf*&) () from /usr/lib/libosgUtil.so.156
#13 0x00007ffff70fe67b in osgUtil::RenderBin::draw(osg::RenderInfo&, osgUtil::RenderLeaf*&) () from /usr/lib/libosgUtil.so.156
#14 0x00007ffff710a58c in osgUtil::RenderStage::drawInner(osg::RenderInfo&, osgUtil::RenderLeaf*&, bool&) () from /usr/lib/libosgUtil.so.156
#15 0x00007ffff710cd27 in osgUtil::RenderStage::draw(osg::RenderInfo&, osgUtil::RenderLeaf*&) () from /usr/lib/libosgUtil.so.156
#16 0x00007ffff710443b in osgUtil::RenderStage::drawPreRenderStages(osg::RenderInfo&, osgUtil::RenderLeaf*&) () from /usr/lib/libosgUtil.so.156
#17 0x00007ffff7118a2f in osgUtil::SceneView::draw() () from /usr/lib/libosgUtil.so.156
#18 0x00007ffff699d5d1 in osgViewer::Renderer::draw() () from /usr/lib/libosgViewer.so.156
#19 0x00007ffff79cd8e9 in osg::GraphicsContext::runOperations() () from /usr/lib/libosg.so.156
#20 0x00007ffff7a67da2 in osg::OperationThread::run() () from /usr/lib/libosg.so.156
#21 0x00007ffff79cf76e in non-virtual thunk to osg::GraphicsThread::run() () from /usr/lib/libosg.so.156
#22 0x00007ffff762d0e9 in OpenThreads::ThreadPrivateActions::StartThread(void*) () from /usr/lib/libOpenThreads.so.21
#23 0x00007ffff333c08c in start_thread () from /usr/lib/libpthread.so.0
#24 0x00007ffff1834e7f in clone () from /usr/lib/libc.so.6

**Comment by openscenegraph** [comment]
I have investigated the issue and come up with a preliminary solution.  I have lots of debug code checking values that I need to clean up and to do more testing before I check in a fix.  This fix will go into OSG master and the 3.6 branch.

**Comment by JDGBOLT** [comment]
Well, just tested the commit for the 3.6 branch, and at the very least it has seemed to fix the crash in the particular circumstances that I encountered. Not 100% sure if it fully fixed the VBO's being used along with display lists, but here is my apitrace which should hopefully show that VBO's are no longer used with Display Lists: https://drive.google.com/open?id=1qpYJBj0x_0KMZOFyQBmjn-LFE_M3IXL4
